# render.yaml
services:
  - type: web
    name: rails-blog
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rails-blog-db
          property: connectionString
    healthCheckPath: /
    numInstances: 1
    autoDeploy: true 
    buildCommand: "./build.sh"
    startCommand: "./start.sh"


databases:
  - name: rails-blog-db
    plan: free
    databaseName: rails_blog_production
    user: rails_blog_user
